apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: tester
        image: enzoyh/teste-repo:latest
        ports:
        - containerPort: 80
        # env:
        # - name: NODE_ENV
        #   value: "production"
        # - name: DATABASE_URL
        #   value: "postgres://user:password@db-host:5432/my-database"
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"
