kind: Service
apiVersion: v1
metadata:
  name: employee-app
  labels:
    app: employee-app
spec:
  type: NodePort
  selector:
    app: employee-app
  ports:
  - port: 80
    targetPort: 80
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: employee-app
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: employee-app
  template:
    metadata:
      labels:
        app: employee-app
        version: v1
    spec:
      containers:
      - name: employee-app
        image: enzoyh/teste-repo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /testando(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: employee-app
                port:
                  number: 80
